Repository IngotGG/iron, pull requests merged in 2024-06, with the labels that each got.

#1 Implement Single & Allow Injecting Coroutine Dispatcher
  .idea/misc.xml
  build.gradle.kts
  src/main/kotlin/gg/ingot/iron/Iron.kt
  src/main/kotlin/gg/ingot/iron/representation/DBMS.kt
  src/main/kotlin/gg/ingot/iron/sql/MappedResultSet.kt
  src/main/kotlin/gg/ingot/iron/transformer/ModelTransformer.kt
  src/main/kotlin/gg/ingot/iron/transformer/ResultTransformer.kt
  src/test/kotlin/DatabaseTest.kt
Labels: enhancement

#2 Implement Connection Pooling
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  build.gradle.kts
  src/main/kotlin/gg/ingot/iron/Iron.kt
  src/main/kotlin/gg/ingot/iron/IronSettings.kt
  src/main/kotlin/gg/ingot/iron/pool/ConnectionPool.kt
  src/main/kotlin/gg/ingot/iron/pool/MultiConnectionPool.kt
  src/main/kotlin/gg/ingot/iron/pool/SingleConnectionPool.kt
  src/main/kotlin/gg/ingot/iron/representation/DBMS.kt
  src/test/kotlin/DatabaseTest.kt
Labels: enhancement

#3 Implement Publishing
  build.gradle.kts
Labels: enhancement

#4 Add Array & Collection Support to Transformer
  gradlew.bat
  src/main/kotlin/gg/ingot/iron/transformer/ResultTransformer.kt
  src/main/kotlin/gg/ingot/iron/transformer/ValueTransformer.kt
Labels: enhancement

#5 Implement Ability To Handle JSON Objects
  build.gradle.kts
  src/main/kotlin/gg/ingot/iron/Iron.kt
  src/main/kotlin/gg/ingot/iron/IronSettings.kt
  src/main/kotlin/gg/ingot/iron/annotations/Column.kt
  src/main/kotlin/gg/ingot/iron/representation/EntityField.kt
  src/main/kotlin/gg/ingot/iron/serialization/SerializationAdapter.kt
  src/main/kotlin/gg/ingot/iron/sql/MappedResultSet.kt
  src/main/kotlin/gg/ingot/iron/transformer/ModelTransformer.kt
  src/main/kotlin/gg/ingot/iron/transformer/ResultTransformer.kt
  src/main/kotlin/gg/ingot/iron/transformer/ValueTransformer.kt
  src/test/kotlin/DatabaseTest.kt
Labels: enhancement

#6 Add Basic README
  CONTRIBUTING.md
  README.md
  src/main/kotlin/gg/ingot/iron/sql/MappedResultSet.kt
Labels: documentation

#7 Implement Custom Column Deserialization Strategies
  src/main/kotlin/gg/ingot/iron/annotations/Column.kt
  src/main/kotlin/gg/ingot/iron/representation/EntityField.kt
  src/main/kotlin/gg/ingot/iron/serialization/ColumnDeserializer.kt
  src/main/kotlin/gg/ingot/iron/transformer/ModelTransformer.kt
  src/main/kotlin/gg/ingot/iron/transformer/ValueTransformer.kt
  src/test/kotlin/DatabaseTest.kt
  src/test/kotlin/DeserializationTest.kt
Labels: enhancement

#8 Utility Extensions for ResultSet
  src/main/kotlin/gg/ingot/iron/sql/ResultSetExt.kt
  src/test/kotlin/DatabaseTest.kt
Labels: enhancement

#9 Don't Block On Connection Release
  src/main/kotlin/gg/ingot/iron/Iron.kt
  src/main/kotlin/gg/ingot/iron/IronSettings.kt
  src/main/kotlin/gg/ingot/iron/pool/MultiConnectionPool.kt
Labels: bug

#12 Enum Column Deserializer
  src/main/kotlin/gg/ingot/iron/serialization/ColumnDeserializer.kt
  src/main/kotlin/gg/ingot/iron/sql/ResultSetExt.kt
  src/main/kotlin/gg/ingot/iron/transformer/ModelTransformer.kt
  src/test/kotlin/DeserializationTest.kt
Labels: enhancement

#15 Iron QoL Additions
  build.gradle.kts
  src/main/kotlin/gg/ingot/iron/Iron.kt
  src/main/kotlin/gg/ingot/iron/IronSettings.kt
  src/main/kotlin/gg/ingot/iron/annotations/Column.kt
  src/main/kotlin/gg/ingot/iron/annotations/Model.kt
  src/main/kotlin/gg/ingot/iron/representation/EntityField.kt
  src/main/kotlin/gg/ingot/iron/representation/EntityModel.kt
  src/main/kotlin/gg/ingot/iron/representation/ExplodingModel.kt
  src/main/kotlin/gg/ingot/iron/serialization/ColumnDeserializer.kt
  src/main/kotlin/gg/ingot/iron/serialization/ColumnSerializer.kt
  src/main/kotlin/gg/ingot/iron/serialization/ColumnTransformer.kt
  src/main/kotlin/gg/ingot/iron/serialization/SerializationAdapter.kt
  src/main/kotlin/gg/ingot/iron/sql/Parameters.kt
  src/main/kotlin/gg/ingot/iron/sql/ResultSetExt.kt
  src/main/kotlin/gg/ingot/iron/sql/controller/Controller.kt
  src/main/kotlin/gg/ingot/iron/sql/controller/ControllerImpl.kt
  src/main/kotlin/gg/ingot/iron/sql/controller/TransactionController.kt
  src/main/kotlin/gg/ingot/iron/strategies/NamingStrategy.kt
  src/main/kotlin/gg/ingot/iron/transformer/ModelTransformer.kt
  src/main/kotlin/gg/ingot/iron/transformer/ResultTransformer.kt
  src/main/kotlin/gg/ingot/iron/transformer/TransformerUtils.kt
  src/main/kotlin/gg/ingot/iron/transformer/ValueTransformer.kt
  src/test/kotlin/DatabaseTest.kt
  src/test/kotlin/DeserializationTest.kt
  src/test/kotlin/ModelTest.kt
Labels: enhancement

#16 Improve library api usage
  .idea/inspectionProfiles/Project_Default.xml
  README.md
  build.gradle.kts
  src/main/kotlin/gg/ingot/iron/Iron.kt
  src/main/kotlin/gg/ingot/iron/serialization/ColumnDeserializer.kt
  src/main/kotlin/gg/ingot/iron/serialization/ColumnSerializer.kt
  src/main/kotlin/gg/ingot/iron/serialization/ColumnTransformer.kt
  src/main/kotlin/gg/ingot/iron/sql/IronResultSet.kt
  src/main/kotlin/gg/ingot/iron/sql/MappedResultSet.kt
  src/main/kotlin/gg/ingot/iron/sql/ResultSetExt.kt
  src/main/kotlin/gg/ingot/iron/sql/controller/Controller.kt
  src/main/kotlin/gg/ingot/iron/sql/controller/ControllerImpl.kt
  src/main/kotlin/gg/ingot/iron/sql/controller/TransactionController.kt
  src/test/kotlin/DatabaseTest.kt
  src/test/kotlin/DeserializationTest.kt
Labels: enhancement
